django/week4/portfolioplus/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('resume/', include('resume.urls', namespace='resume')),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
    path('admin/', admin.site.urls),
]

django/week4/resume/urls.py
"""
portfolioplus/resume/urls.py for the resume app in portfolioplus
Tiffany
02/10/2018
"""

from django.urls import path

from . import views

app_name = 'resume'
urlpatterns = [
    path('', views.home, name='resume'),
]

django/week4/resume/models.py
from django.db import models

# Create your models here.

class Resume(models.Model):
	first_name = models.CharField(max_length=25, null=False, blank=False)
	last_name = models.CharField(max_length=25, null=True, blank=True)

	def get_full_name(self):
		return "{} {}".format(self.first_name, self.last_name)

	def get_last_name_first_name(self):
		return "{}, {}".format(self.last_name, self.first_name)

	def get_experience(self):
		return self.experience_set.all()

	def get_education(self):
		return self.education_set.all()

	def __str__(self):
		return self.last_name


class Experience(models.Model):
	parent_resume = models.ForeignKey('Resume', on_delete=models.CASCADE, default=1)
	title = models.CharField(max_length=60, null=False, blank=False)
	location = models.CharField(max_length=60, null=False, blank=True)
	start_date = models.DateField(null=True, blank=True)
	end_date = models.DateField(null=True, blank=True)
	description = models.TextField(null=False, blank=True)

	def __str__(self):
		return self.title

class Education(models.Model):
	parent_resume = models.ForeignKey('Resume', on_delete=models.CASCADE, default=1)
	institution_name = models.CharField(max_length=60, null=False, 
		blank=False)
	location = models.CharField(max_length=60, null=False, blank=True)
	degree = models.CharField(max_length=60, null=False, blank=True)
	major = models.CharField(max_length=60, null=False, blank=True)
	gpa = models.FloatField(null=False, blank=True)

	def __str__(self):
		return self.institution_name

django/week4/portfolioplus/views.py
"""
portfolioplus/views.py for the portfolioplus Python package in week 3 container
Tiffany
02/10/2018
"""

from django.shortcuts import render

def home(request):
	"""
	Takes request of type HttpRequest and calls render() with ustudy.html file and empty context.
	request: has information about current request that triggered this view
	Returns: home page of week 2 portfolio site
	"""
	
	context = {}
	return render(request, 'home.html', context)


def resume(request):
	"""
	Takes request of type HttpRequest and calls render() with ustudy.html file and empty context.
	request: has information about current request that triggered this view
	Returns: resume page of week 2 portfolio site
	"""

	context = {}
	return render(request, 'resume.html', context)


def portfolio(request):
	"""
	Takes request of type HttpRequest and calls render() with ustudy.html file and empty context.
	request: has information about current request that triggered this view
	Returns: portfolio page of week 2 portfolio site
	"""

	context = {}
	return render(request, 'portfolio.html', context)


def contact(request):
	"""
	Takes request of type HttpRequest and calls render() with ustudy.html file and empty context.
	request: has information about current request that triggered this view
	Returns: contact page of week 2 portfolio site
	"""

	context = {}
	return render(request, 'contact.html', context)

django/week4/resume/views.py
"""
portfolioplus/resume/views.py for the resume app in portfolioplus
Tiffany
02/10/2018
"""

from django.shortcuts import render
from .models import Resume, Experience, Education

# Create your views here.
def home(request):
	"""
	Returns the resume app resume template.
	"""
	r1 = Resume.objects.first()
	context = {'my_resume': r1}
	return render(request, 'resume/resume.html', context)

django/week4/resume/templates/resume/resume.html
<!-- portfolioplus/resume/templates/resume.html -->
{% extends 'base.html' %}
{% block title %}Resume{% endblock %}

{% block content %}
<p>Experience</p>
<p>
  {% if my_resume %}
  <table border = "1" width = "100%">
    {% for exp in my_resume.get_experience %}
      <tr>
      <td colspan = "2">{{exp.title}}</td>
      </tr>
      <tr>
        <td>{{exp.location}}</td>
        <td>{{exp.start_date}} to {{exp.end_date}}</td>
      </tr>
      <tr>
      <td colspan = "2">{{exp.description}}</td>
      </tr>
    {% endfor %}
  </table>
  {% else %}
    <h2>No Experience found.</h2>
  {% endif %}
</p>
<p>Education</p>
<p>
  {% if my_resume %}
  <table border = "1" width = "100%">
    {% for edu in my_resume.get_education %}
      <tr>
      <td colspan = "2">{{edu.degree}}: {{edu.major}}</td>
      </tr>
      <tr>
        <td>{{edu.institution_name}}</td>
        <td>{{edu.location}}</td>
      </tr>
      <tr>
      <td colspan = "2">GPA: {{edu.gpa}}</td>
      </tr>
    {% endfor %}
  </table>
  {% else %}
    <h2>No Education found.</h2>
  {% endif %}
</p>
{% endblock %}

django/week4/templates/base.html
{% load static %}
<!-- portfolioplus/templates/base.html -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel='stylesheet' href="{% static 'css/nav.css' %}" />
	<link rel='stylesheet' href="{% static 'css/style.css' %}" />
</head>
<body>
	<nav>
		<a href="{% url 'home' %}">Home</a>
		<a href="{% url 'resume:resume' %}">Resume</a>
		<a href="{% url 'portfolio' %}">Portfolio</a>
		<a href="{% url 'contact' %}">Contact</a>
	</nav>
{% block content %}{% endblock %}

{% block footer %}{% endblock %}
</body>
</html>

django/week4/templates/contact.html
<!-- portfolioplus/templates/contact.html -->
{% extends 'base.html' %}
{% block title %}Contact Us{% endblock %}

{% block content %}
	<form>
		First name:<br>
		<input type="text" name="firstname" value="">
		<br>
		Last name:<br>
		<input type="text" name="lastname" value="">
		<br>
		Message:<br>
		<textarea name="message" rows="10" cols="50"></textarea>
		<br><br>
		<input type="submit" value="Submit">
		<input type="reset">
	</form> 

<p>Click the "Reset" button to reset the form values.</p>
{% endblock %}

django/week4/templates/home.html
<!-- portfolioplus/templates/home.html -->
{% extends 'base.html' %}
{% block title %}Portfolio Site{% endblock %}

{% block content %}
	<div id="container">
		<h1>Welcome to Tiffany's portfolio site!</h1>
		<p>Feel free to browse for content and inspiration.</p>
	</div>
{% endblock %}

django/week4/templates/portfolio.html
<!-- portfolioplus/templates/portfolio.html -->
{% extends 'base.html' %}
{% block title %}My Portfolio{% endblock %}
{% load static %}
{% block content %}
<link rel='stylesheet' href="{% static 'css/portfolio.css' %}" />
<!-- MAIN (Center website) -->
<div class="main">

<h1>Tiffany's Portfolio</h1>
<hr>

<h2>PORTFOLIO</h2>

<!-- Portfolio Gallery Grid -->
<div class="row">
  <div class="column">
    <div class="content">
      <img src="{% static 'images/cakepop.jpg' %}" alt="Cake Pops" style="width:100%">
      <h3>Cake Pops</h3>
      <p>French sugar cake pops.</p>
    </div>
  </div>
  <div class="column">
    <div class="content">
      <img src="{% static 'images/chocolate.jpg' %}" alt="Chocolate Dream" style="width:100%">
      <h3>Chocolate Dream</h3>
      <p>Created using the finest chocolates.</p>
    </div>
  </div>
  <div class="column">
    <div class="content">
      <img src="{% static 'images/candybar.jpg' %}" alt="Candy Bar" style="width:100%">
      <h3>Candy Bar</h3>
      <p>Beautiful candy bar for a wedding.</p>
    </div>
  </div>
  <div class="column">
    <div class="content">
      <img src="{% static 'images/icecream.jpg' %}" alt="Ice Cream Treats" style="width:100%">
      <h3>Ice Cream Treats</h3>
      <p>Adorable ice cream treats.</p>
    </div>
  </div>
<!-- END Grid -->
</div>

<!-- END MAIN -->
</div>
{% endblock %}

django/week4/templates/resume.html
<!-- portfolioplus/templates/resume.html -->
{% extends 'base.html' %}
{% block title %}Resume{% endblock %}

{% block content %}
<p>Tiffany's Resume</p>
<p>
	<table border = "1" width = "100%">
        <thead>
        	<tr>
            	<td colspan = "4">Head Candy Maker</td>
            </tr>
        </thead>
        <tbody>
        	<tr>
               <td>Spun</td>
               <td>London, England</td>
               <td>2015-Present</td>
               <td><a href="https://www.spun-candy.com" target="_blank">Website</a></td>
            </tr>
        <!--<tfoot>-->
            <tr>
               <td colspan = "4">
               	<ul>
               		<li>Custom orders</li>
               		<li>Bake</li>
               		<li>Decorate</li>
               		<li>Candy-making</li>
               		<li>Chocolate-making</li>
               		<li>Sales</li>
               	</ul>
               </td>
            </tr>
        <!--</tfoot>-->
         
        <!--<tbody>-->
            
        <!--</tbody>-->
        <!--<thead>-->
        	<tr>
            	<td colspan = "4">Associate Candy Maker</td>
            </tr>
        <!--</thead>-->
        	<tr>
               <td>Sugar Factory</td>
               <td>New York, NY</td>
               <td>2012-2015</td>
               <td><a href="https://sugarfactory.com" target="_blank">Website</a></td>
            </tr>
        <!--<tfoot>-->
            <tr>
               <td colspan = "4">
               	<ul>
               		<li>Assist with custom orders</li>
               		<li>Assist with decorating</li>
               		<li>Candy-making</li>
               		<li>Chocolate-making</li>
               	</ul>
               </td>
            </tr>
        <!--</tfoot>-->
         
       <!--<tbody>-->
            
        </tbody>
        
    </table>
</p>
{% endblock %}